[package]
name = "piggies"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
bytemuck = "1.25.2"
cgmath = "0.18.0"
env_logger = "0.11.11"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
log = "0.4.33"
pollster = "1.0.1"
tobj = "4.0.5"
wgpu = "30.0.0"
winit = "0.30.13"

[build-dependencies]
anyhow = "1.0.104"
fs_extra = "1.2"
glob = "0.3"
